### ISSUE TITLE
way to limit gain to 0db?

### ISSUE THREAD

**Issue by PovilasLT** [Jaggernaut555/midi-mixer-voicemeeter#1]
Hello,
is there a way to limit sliders/knobs to 0db in voicemeeter?
Selection "Limit Remote Gain to 0dBfs" in voicemeeter not making any difference.
Maybe you can add setting to limit gain? On nanoKontrol2 with small faders it's hard to find 0db. Thanks!

**Comment by Jaggernaut555** [comment]
Enabling the "Limit Remote Gain to 0dBfs" setting on Voicemeeter Potato version 3.0.1.8 is working for me. It even if I keep turning my fader up it doesn't set it higher than 0db.

What version of Voicemeeter are you using?

**Comment by PovilasLT** [comment]
Voicemeeter Potato 3.0.2.1
Video: https://streamable.com/tjda5i

**Comment by PovilasLT** [comment]
Also, i noticed that Voicemeeter sliders doesn't activate Midi Mixer OSD.

**Comment by Jaggernaut555** [comment]
Looks like you're also on Windows 11? I wonder if that has something to do with this setting not working. (Verification that this is working on my version: https://streamable.com/s8wk8u ) I could possibly make a "max db" setting that would allow a customizable arbitrary number to max out the sliders at.

As for no OSD that's currently just a limit of midi-mixer plugins. Jack has said he's planning/working on allowing plugins to use the OSD in a future update. Whenever it works I will be adding it to this plugin.

**Comment by PovilasLT** [comment]
Yeah, i'm on Windows 11. If I use nanokontrol without midi mixer (connecting to voicemeeter), limit setting works, so i don't think that issue is with voicemeeter.

**Comment by Jaggernaut555** [comment]
The reason I'm thinking it's something on voicemeeter's end is that it's supposed to limit incoming values itself. The client application/controller isn't supposed to have to deal with it. I may end up updating my install to see if something was changed in the API between versions 3.0.1.8 and 3.0.2.1.

On fixing the issue as it stands, whenever I get time I'll add the ability to set a "max db" value on the plugin's setting page as that would be useful to set any limit including 0db.

**Comment by Jaggernaut555** [comment]
This feature is added in the newest release [here](https://github.com/Jaggernaut555/midi-mixer-voicemeeter/releases)

**Comment by PovilasLT** [comment]
@Jaggernaut555 small issue after update, value 0 doesn't work in maxdb setting, needs to be something like 0.01 to make difference. If it's set to 0, it will still go all the way to +12db. 
Also, thanks, very helpful update! :)

**Comment by Jaggernaut555** [comment]
That was my mistake. When handling the empty settings value I accidentally ended up messing up handling specifically zero. New build has fixed it.

**Comment by Jaggernaut555** [comment]
@PovilasLT I updated voicemeeter to the newest version 3.0.2.1 and the `Limit Remote Gain to 0dBfs` setting no longer works for me. I'm going to bring this up on their forums but that answers the question of why it wasn't working.
