### ISSUE TITLE
Feature Request - Add ability to toggle output

### ISSUE THREAD

**Issue by corvus2606** [Jaggernaut555/midi-mixer-voicemeeter#10]
Would it be possible to add a function to the buttons to toggle the output options, an example would be to replace the macro button I currently use which sends the command:

strip(0).A1=1;

Ideally this would be able to be assigned for all output busses for each strip

**Comment by Jaggernaut555** [comment]
Sorry I had missed this a while ago. I've just added this feature in version 1.5.0
