### ISSUE TITLE
Feature request: assign Strip[i].Limit to knob X 

### ISSUE THREAD

**Issue by mipsou** [Jaggernaut555/midi-mixer-voicemeeter#13]
Hi,
Is it possible to assign limit to knob ( Strip[i].Limit )?
![image](https://github.com/user-attachments/assets/08cd4194-c777-483d-ad7a-2668ecc1b450)

regards

**Comment by Jaggernaut555** [comment]
Currently this isn't something you can set but it should be possible to make.

To be clear you mean to have a knob/fader go up/down to raise or lower the limit?

**Comment by mipsou** [comment]
In X-TOUCH Extender you have fader on top. I want to use this control to ajust Strip0.Limit
I don't think it's complicated because it's native to the voicemeter macro.

**Comment by Jaggernaut555** [comment]
Added this in [release 1.6.0](https://github.com/Jaggernaut555/midi-mixer-voicemeeter/releases/tag/v1.6.0).

Enable the setting then in "groups" there should be new options to set on a fader/knob. Minimum value on the fader is -40db Limit and max is 12db (no limit)
