### ISSUE TITLE
Feature request: Change output with unused Record button

### ISSUE THREAD

**Issue by PovilasLT** [Jaggernaut555/midi-mixer-voicemeeter#3]
Hello,
after updates, R (record) button seems to no longer toggle Solo mode for input. Feature to change outputs (A1-A5, B1-B3) with that button would be very useful. Similar idea is on [Midi Mixer roadmap](https://trello.com/c/7vvEYcmG/45-be-able-to-change-cycle-the-output-device-of-an-assigned-application-with-a-button), but it's still in Exploring category. Is this change possible? :)

**Comment by Jaggernaut555** [comment]
Thanks for spotting the solo bug. It has been fixed.

As for the setting the output: I have looked into making this feature, it's currently in the `extra-buttons` branch of code. Allowing toggling of different outputs per strip. The main downside of this that made me hesitant to add it right now is that this would add 64 options to the button lists.  I was hoping the button selection UI would be updated before I published this change but I might finish it before that happens.
![image](https://user-images.githubusercontent.com/5661214/149417352-6a52ae95-f103-4cdb-ac4e-3f7fb33d5fce.png)

I went for this approach over having some sort of cycling with a single button as there's no way for one button to handle the many different states a user may want. (e.g. send strip 1 to A1, A3, and B3)

**Comment by PovilasLT** [comment]
Thanks for the fix, you da real mvp! :D 

for output, maybe then it would be more simple to use VB Macro buttons?
There are 2 position buttons with logical ID, so maybe there is possibillity to activate them and change midi pad LED status? You can add 16 VB Macro buttons, that would be enough for most of people, i think.

http://puu.sh/ICsUk/80915948e4.png

**Comment by PovilasLT** [comment]
As I see on OSB plugin, it's possible to get list from program, so maybe there is a way to take macro buttons list from VB?

![ss (2022-01-14 at 02 46 43)](https://user-images.githubusercontent.com/16564979/149432010-1c128480-e3ef-4032-8ee9-222e617aa85d.png)

**Comment by Jaggernaut555** [comment]
The way I have these buttons set up now is more like a "mute" button for each input to each output. To do anything with multiple state changes on one button I think macro buttons would be the more practical solution. I can't make built in buttons for every scenario but I can at least put the most basic use case in.

Looking at the voicemeeter API I think it may be possible to interact with macro buttons. I'll have to do some testing on it.

**Comment by Jaggernaut555** [comment]
After doing some testing with the voicemeeter DLL it seems the ability to interact with macro buttons is extremely limited.

It basically only works on buttons configured in `2 Positions` (AKA Toggle) mode. You can kind of get around this by adding `Command.Button[whatever button index].State = 0` to a `PUSH` mode button but most people will not know that this step is required. Support for that command also only work on newer versions of voicemeeter. On top of that there's no way to get even basic information like the macro button names.

This is rather disappointing but hopefully the features will be expanded in the future.

**Comment by 1Tomber** [comment]
The new VM Streamer View application only uses buses, that got a custom name (which took me some time to find out how to do), which is quite clever to determine the used buses. This could help declutter the amount of actions.

PS: edit name by right clicking the slider

**Comment by PovilasLT** [comment]
Coming back to this with some new ideas. What about to add ability to change all three buttons actions in settings? 
That way you wouldn't need to add 64 options.
Available buttons: Assign, Run, Mute
Available actions in VM: Mono, Mute, Solo, Buses (A1-A5, B1-B3).

So in settings user could set that Assign button would toggle bus A3 for example. I think that would fulfill most users needs, because anyway there are most cases when few buses are used (mostly 2, one for monitoring and one for prod).
For more advanced settings, it could be text field rather than dropdown, so user can enter combination of actions that button would do, i.e.:
Assign: Mute,Solo
Run: A1,A2,A5
Mute: A3,A4,B2,B3
and by that way plugin would send all commands to VM by that button press.
What do you think, @Jaggernaut555 ?

**Comment by Jaggernaut555** [comment]
@PovilasLT That could be one way to do it, alternatively I could do something similar to how I got around a similar issue in my Push-To-Talk plugin. Something like having a text field where you could add something like

```
Strip1:A1,A2,B1;Strip2:B1
```

Then that would add options to the buttons menu to toggle strip1 going to A1, A2, and B2. As well as a button to toggle Strip2 going to B1.

The way I use voicemeeter (potato version) I have ~4 different toggles I use regularly and need individual control for, right now just using hotkeys and voicemeeter's macrokeys. This way would not have to decide to remove either the solo or mute options but wouldn't be as simple for doing a multi-bus-toggle on one click (though that would still be possible by duplicating the button in midi-mixer and adding another command to it).

**Comment by PovilasLT** [comment]
@Jaggernaut555  I'm thinking best way is to add 2 or 3 text fields (I don't know if it's possible to use Assign button also) with current default values:

Assign (if possible): `Assign`
Mute: `Mute`
Run: `Run`

and more advanced users could change these values as they need, i.e.:
Assign: `Assign`
Mute: `A1,A2,A3`
Run: `B1,B2`
also adding indicator lights if buses are active.

I'm still thinking that most users won't need separate outputs for separate strips, in most cases there is Live and Monitor buses, and all inputs are routed same way. Doing this would still retain same functionality for users that are not interested in bus toggling.

**Comment by Jaggernaut555** [comment]
This has been added as of version 1.5.0. Both the options that PovilasLT and I have mentioned here are available to use for audio routing.
