### ISSUE TITLE
Issues with plugin when used with start on boot

### ISSUE THREAD

**Issue by zford** [Jaggernaut555/midi-mixer-voicemeeter#4]
When both Voicemeeter and MIDI mixer are configured as "start on boot", the MIDI Mixer Voicemeeter Plugin does not load correctly. Configured knobs don't show up under profile in MIDI Mixer. Physical knobs also do not work on MIDI device.

Error message is thrown on startup as follows:
_Voicemeeter Plugin failed to connect_

As workaround, going into MIDI Mixer and disabling and re-enabling the Voicemeeter Plugin restores functionality.

Voicemeeter Version: 3.0.2.1
MIDI Mixer Version: 2.7.0
MIDI Mixer Voicemeeter Plugin Version: 1.2.2

**Comment by zford** [comment]
My assumption is that that the MIDI Mixer application and Voicemeeter plugin is starting too quickly and not giving enough time for the Voicemeeter application to finish starting up on boot. Assuming it's not possible to detect when Voicemeeter application is ready on system boot, some kind of retry logic on the plugin side may be warranted.

**Comment by Jaggernaut555** [comment]
Yeah the issue is the application startup order. I've tried some retrying code but it wasn't behaving correctly.

**Comment by Jaggernaut555** [comment]
An update included in [v1.3.2](https://github.com/Jaggernaut555/midi-mixer-voicemeeter/releases/tag/v1.3.2) should fix this. If Voicemeeter is installed but just not running it will try again after a delay. This should help with not having to worry about application startup order.

**Comment by zford** [comment]
I tried out v1.3.2 and this appears to be fixed. Tried a few reboots, some testing and everything looks good.
