### ISSUE TITLE
Jumping/skipping fader when rapidly changing volume

### ISSUE THREAD

**Issue by 1Tomber** [Jaggernaut555/midi-mixer-voicemeeter#6]
When using a rotary encoder and turning it rapidly, the fader is jumping/skipping and volume control is not reliable. This is probably happening on slow changes as well, bus less apparent.

Possible Solution: Don't update/set volume from voicemeeter for a bus, when there is a volume change happening, as I guess that the volume in the plugin is updated to a pre volume change level from voicemeeter.

This is how it looks with a Behringer x-touch mini with endless rotary encoder, spinning fast:
https://user-images.githubusercontent.com/24652659/157726793-623d44f3-0fd1-40b0-90c7-9009ef5bf1db.mp4

**Comment by Jaggernaut555** [comment]
Good catch. I typically use faders and not encoders so I didn't notice this behaviour. Should be a simple fix when I have time.

**Comment by Jaggernaut555** [comment]
New release [v1.3.3](https://github.com/Jaggernaut555/midi-mixer-voicemeeter/releases/tag/v1.3.3) should fix this issue.
